spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mamaxiang?characterEncoding=UTF-8&serverTimezone=UTC&rewriteBatchedStatements=true
    username: root
    password: 123456
  application:
    name: backend_sy
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher # 解决SpringBoot与Swagger版本冲突
  redis:
    host: localhost
    port: 6379
    #    password: 123456
    lettuce:
      pool:
        max-wait: 100 # 连接等待时间
        max-active: 8 # 最大连接数
        min-idle: 0 # 最小空闲连接数
        max-idle: 8 # 最大空闲连接数
  jackson:
    default-property-inclusion: non_null # JSON处理时忽略非空字段
  servlet:
    multipart:
      max-file-size: 10MB # 单文件最大上传大小
      max-request-size: 100MB # 多文件最大上传大小
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl # 开启日志，输出SQL语句
server:
  port: 8081 # 指定端口号
  servlet:
    context-path: "/api" # 指定根路径


